# See https://docs.astral.sh/ruff/rules/ for meaning of rules
[tool.ruff]
line-length = 119
extend-exclude = ["*.bat", "gw2_logs_archive/gw2_logs/migrations/*"]

[tool.ruff.lint]
select = ["D", "E", "F", "NPY", "PD", "C4", "I"]
ignore = ["D1", "D202", "D205", "D400", "D404", "E501", "PD002", "PD901"]
# Apply isort rules, but not others like removing unused imports.
fixable = ["I"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401",  "I001"]