# Generated by Django 4.2.8 on 2023-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='type',
            field=models.CharField(choices=[('CDMA', 'CDMA'), ('GSM', 'GSM'), ('GSM/CDMA', 'GSM/CDMA')], default='raid', max_length=10),
        ),
    ]
