# Generated by Django 4.2.8 on 2023-12-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0005_raidclears_dpslogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DpsLogs',
            new_name='DpsLog',
        ),
        migrations.RenameModel(
            old_name='RaidClears',
            new_name='RaidClear',
        ),
    ]
