# Generated by Django 4.2.8 on 2023-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0007_rename_title_raidclear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='boss_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='boss_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='cm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='gw2_build',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='players',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='discord_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raidclear',
            name='discord_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
