# Generated by Django 4.2.8 on 2023-12-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0009_alter_dpslog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
