# Generated by Django 4.2.8 on 2023-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0010_alter_dpslog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
