# Generated by Django 4.2.8 on 2023-12-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0011_emoji_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to='gw2_logs.emoji'),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='clear_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clear', to='gw2_logs.raidclear'),
        ),
    ]
