# Generated by Django 4.2.8 on 2023-12-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0020_alter_dpslog_boss_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpslog',
            old_name='boss_id',
            new_name='encounter',
        ),
    ]
