# Generated by Django 4.2.8 on 2023-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0021_rename_boss_id_dpslog_encounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceClear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('discord_message_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='cm',
        ),
    ]
