# Generated by Django 4.2.8 on 2023-12-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0022_instanceclear_remove_encounter_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpslog',
            name='clear_id',
        ),
        migrations.AddField(
            model_name='dpslog',
            name='group_clear_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps_logs', to='gw2_logs.raidclear'),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='instance_clear_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps_logs', to='gw2_logs.instanceclear'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
