# Generated by Django 4.2.8 on 2023-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0023_remove_dpslog_clear_id_dpslog_group_clear_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
