# Generated by Django 4.2.8 on 2023-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0025_rename_group_clear_id_dpslog_group_clear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceclear',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instanceclear',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raidclear',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
