# Generated by Django 4.2.8 on 2023-12-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0026_alter_instanceclear_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='gw2_logs.emoji'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='gw2_logs.emoji'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='gw2_logs.instance'),
        ),
    ]
