# Generated by Django 4.2.8 on 2023-12-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0027_instance_emoji_alter_encounter_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceclear',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_clears', to='gw2_logs.instance'),
        ),
    ]
