# Generated by Django 4.2.8 on 2023-12-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0030_dpslog_json_dump'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaidClear',
            new_name='InstanceClearGroup',
        ),
        migrations.AddField(
            model_name='instanceclear',
            name='instance_clear_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_clears', to='gw2_logs.instancecleargroup'),
        ),
    ]
