# Generated by Django 4.2.8 on 2023-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0033_dpslog_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='local_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
