# Generated by Django 4.2.8 on 2023-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0034_dpslog_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceclear',
            name='success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
