# Generated by Django 4.2.8 on 2023-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0035_instanceclear_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gw2_id', models.CharField(blank=True, max_length=100, null=True)),
                ('guild', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
