# Generated by Django 4.2.8 on 2023-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0038_player_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='core_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
