# Generated by Django 4.2.8 on 2023-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0039_dpslog_core_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='core_player_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
