# Generated by Django 4.2.8 on 2024-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0046_instance_discord_leaderboard_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
