# Generated by Django 4.2.8 on 2024-01-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0047_instance_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='has_cm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
