# Generated by Django 4.2.8 on 2024-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0048_encounter_has_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='shortname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
