# Generated by Django 4.2.8 on 2024-01-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0049_encounter_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='lb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='lb_cm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
