# Generated by Django 4.2.8 on 2024-01-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0051_dpslog_emboldened_dpslog_final_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpslog',
            old_name='final_health',
            new_name='final_health_percentage',
        ),
    ]
