# Generated by Django 4.2.8 on 2024-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0052_rename_final_health_dpslog_final_health_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceclear',
            name='discord_message_id',
        ),
        migrations.AddField(
            model_name='instanceclear',
            name='use_in_rank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
