# Generated by Django 4.2.8 on 2024-01-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0053_remove_instanceclear_discord_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['type', 'nr']},
        ),
        migrations.AlterModelOptions(
            name='instanceclear',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='instanceclear',
            name='use_in_rank',
        ),
    ]
