# Generated by Django 4.2.8 on 2024-01-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0054_alter_instance_options_alter_instanceclear_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceclear',
            name='emboldened',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
