# Generated by Django 4.2.8 on 2024-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0061_instanceclear_core_player_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='type',
            field=models.CharField(choices=[('raid', 'Raid'), ('fractal', 'Fractal'), ('strike', 'Strike'), ('medal', 'Medal'), ('other', 'Other')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='type',
            field=models.CharField(choices=[('raid', 'Raid'), ('fractal', 'Fractal'), ('strike', 'Strike'), ('golem', 'Golem')], default='raid', max_length=10),
        ),
    ]
