# Generated by Django 4.2.8 on 2024-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0062_emoji_type_alter_instance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='png_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
