# Generated by Django 4.2.8 on 2024-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0064_discordmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='folder_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
