# Generated by Django 4.2.8 on 2024-03-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0067_instance_discord_message_instancegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='instance_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_groups', to='gw2_logs.instancegroup'),
        ),
    ]
