# Generated by Django 4.2.8 on 2024-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0075_dpslog_phasetime_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='legendary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
