# Generated by Django 4.2.8 on 2024-04-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0076_dpslog_legendary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
