# Generated by Django 4.2.8 on 2024-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0081_rename_use_in_instance_group_encounter_leaderboard_instance_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpslog',
            old_name='legendary',
            new_name='lcm',
        ),
        migrations.AddField(
            model_name='emoji',
            name='discord_id_lcm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emoji',
            name='url_lcm',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='has_lcm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='lb_lcm',
            field=models.BooleanField(blank=True, null=True, verbose_name='leaderboard lcm'),
        ),
    ]
