# Generated by Django 4.2.8 on 2024-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0082_rename_legendary_dpslog_lcm_emoji_discord_id_lcm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='guild',
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('core', 'Core'), ('friend', 'Friend')], default=None, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
    ]
