# Generated by Django 4.2.8 on 2024-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0083_remove_player_guild_player_role_delete_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='friend_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceclear',
            name='friend_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancecleargroup',
            name='friend_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
