# Generated by Django 5.1.6 on 2025-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0085_alter_discordmessage_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpslog',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='final_health_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
