# Generated by Django 5.1.6 on 2025-02-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0086_remove_dpslog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='final_health_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='discord_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='gw2_logs.discordmessage', verbose_name='discord message leaderboard'),
        ),
        migrations.AlterField(
            model_name='instancegroup',
            name='discord_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_group', to='gw2_logs.discordmessage', verbose_name='discord message leaderboard'),
        ),
    ]
