# Generated by Django 5.1.6 on 2025-02-08 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0087_alter_dpslog_final_health_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
