# Generated by Django 5.1.6 on 2025-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0088_discordmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancecleargroup',
            name='discord_message_id_old',
        ),
        migrations.AddField(
            model_name='instancecleargroup',
            name='duration_encounters',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
