# Generated by Django 5.1.6 on 2025-02-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0091_alter_encounter_has_cm_alter_encounter_has_lcm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='leaderboard_instance_group',
        ),
    ]
