# Generated by Django 5.1.6 on 2025-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0092_remove_encounter_leaderboard_instance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='use_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
