# Generated by Django 5.1.6 on 2025-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0093_dpslog_use_in_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='cm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='emboldened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='lcm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dpslog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='animated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instanceclear',
            name='emboldened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instanceclear',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instancecleargroup',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
