# Generated by Django 5.1.6 on 2025-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0094_alter_dpslog_cm_alter_dpslog_emboldened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='weekdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
