# Generated by Django 5.1.6 on 2025-03-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0095_discordmessage_weekdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='weekdate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
