# Generated by Django 5.1.6 on 2026-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0096_alter_discordmessage_weekdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='health_timers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
