# Generated by Django 5.1.6 on 2026-02-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0097_dpslog_health_timers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpslog',
            name='phasetime_str',
        ),
    ]
