# Generated by Django 5.1.6 on 2026-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0098_remove_dpslog_phasetime_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='is_progression_log',
            field=models.BooleanField(default=False),
        ),
    ]
