# Generated by Django 5.1.6 on 2026-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0099_dpslog_is_progression_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='enrage_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
