# Generated by Django 5.1.6 on 2026-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0100_encounter_enrage_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
