# Generated by Django 5.1.6 on 2026-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0101_alter_encounter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecleargroup',
            name='discord_messages',
            field=models.ManyToManyField(blank=True, related_name='instance_clear_groups', to='gw2_logs.discordmessage'),
        ),
    ]
