# Generated by Django 5.1.6 on 2026-03-01 20:54

from django.db import migrations, models

def copy_discord_message_to_many_to_many(apps, schema_editor):
    InstanceClearGroup = apps.get_model("gw2_logs", "InstanceClearGroup")
    for group in InstanceClearGroup.objects.all():
        if group.discord_message:
            group.discord_messages.add(group.discord_message)

class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0102_instancecleargroup_discord_messages'),
    ]

    operations = [
        migrations.RunPython(copy_discord_message_to_many_to_many),
    ]
