# %%
import logging  # noqa:F401
import logging.config
import os
from pathlib import Path

from bot_settings.env_settings import BaseEnvSettings, EnvSettings

logger = logging.getLogger(__name__)

PROJECT_DIR = Path(__file__).resolve().parents[2]  # git repo

# Load .env settings
base_settings = BaseEnvSettings.load()
env_settings = EnvSettings.load(app_env=base_settings.APP_ENV)


# Use pydantic-loaded settings instead of direct env reads
DISCORD_API_SECRET = base_settings.DISCORD_API_TOKEN

WEBHOOKS = {
    "raid": env_settings.WEBHOOK_BOT_CHANNEL_RAID,
    "strike": env_settings.WEBHOOK_BOT_CHANNEL_STRIKE,
    "fractal": env_settings.WEBHOOK_BOT_CHANNEL_FRACTAL,
    "leaderboard": env_settings.WEBHOOK_BOT_CHANNEL_LEADERBOARD,
    "cerus_cm": env_settings.WEBHOOK_BOT_CHANNEL_CERUS_CM,
}

WEBHOOKS_CURRENT_WEEK = {
    "raid": env_settings.WEBHOOK_BOT_CHANNEL_RAID_CURRENT_WEEK,
    "strike": env_settings.WEBHOOK_BOT_CHANNEL_STRIKE_CURRENT_WEEK,
    "fractal": None,  # Not used
}

# Required for navigation menu, retrieve manually from discord
DISCORD_CHANNELS = {"leaderboard": env_settings.CHANNEL_ID_LEADERBOARD}

for key in WEBHOOKS_CURRENT_WEEK.keys():
    if WEBHOOKS_CURRENT_WEEK[key] == "optional":
        WEBHOOKS_CURRENT_WEEK[key] = None


LEADERBOARD_THREADS = {  # thread channel ids in discord.
    "raid": env_settings.WEBHOOK_BOT_THREAD_LEADERBOARD_RAIDS,
    "strike": env_settings.WEBHOOK_BOT_THREAD_LEADERBOARD_STRIKES,
    "fractal": env_settings.WEBHOOK_BOT_THREAD_LEADERBOARD_FRACTALS,
}

CORE_MINIMUM = {
    "raid": base_settings.CORE_MINIMUM_RAID,
    "strike": base_settings.CORE_MINIMUM_STRIKE,
    "fractal": base_settings.CORE_MINIMUM_FRACTAL,
}
INCLUDE_NON_CORE_LOGS = base_settings.INCLUDE_NON_CORE_LOGS  # Include non core logs on leaderboards

DPS_REPORT_USERTOKEN = base_settings.DPS_REPORT_USERTOKEN
MEAN_OR_MEDIAN = base_settings.MEAN_OR_MEDIAN
MEDALS_TYPE = base_settings.MEDALS_TYPE  # Options=['original', 'percentile', 'newgame']
RANK_BINS_PERCENTILE = base_settings.RANK_BINS_PERCENTILE  # Distribution of percentile bins.
# Defaults to [20, 40, 50, 60, 70, 80, 90, 100]. This means if a log is faster than
# 90% to 100% of other logs, it will be assigned to the last bin.

DEBUG = env_settings.DEBUG
LOGLEVEL = env_settings.LOGLEVEL


if DEBUG:
    LOGFORMAT = "%(asctime)s|%(levelname)-8s| %(module)-30s:%(lineno)-4d| %(message)s"
    # LOGFORMAT = "%(asctime)s|%(levelname)-8s| %(name)s:%(lineno)-4d| %(message)s"  # name could get a bit long.
else:
    LOGFORMAT = "%(asctime)s|%(levelname)-8s| %(message)s"


BASE_DIR = Path(__file__).resolve().parents[1]  # gw2_logs_archive
EI_PARSED_LOGS_DIR = PROJECT_DIR.joinpath("Data", "parsed_logs")


DPS_LOGS_DIR = base_settings.DPS_LOGS_DIR

EXTRA_LOGS_DIR = base_settings.EXTRA_LOGS_DIR
# Shared drive with other static members, they can post logs there to upload.


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": LOGFORMAT,
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "null": {
            "class": "logging.NullHandler",
        },
        "console": {
            "level": "NOTSET",
            "formatter": "standard",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
        },
        "stderr": {
            "level": "ERROR",
            "formatter": "standard",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
        },
    },
    "loggers": {
        "": {  # root logger
            "level": "WARNING",
            "handlers": ["console", "stderr"],
        },
        "__main__": {
            "level": "DEBUG",
        },
        "scripts": {
            "level": LOGLEVEL,
        },
        "gw2_logs": {
            "level": LOGLEVEL,
        },
    },
}
# Django will do this by default, but easier to follow if its explicit.
logging.config.dictConfig(LOGGING)

logger = logging.getLogger(__name__)

if not DPS_LOGS_DIR.exists():
    logger.warning("ArcDPS folder not found. Set the DPS_LOGS_DIR variable in the .env")

"""
Django settings for gw2_logs_archive project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = base_settings.DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "gw2_logs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bot_settings.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bot_settings.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "NAME": env_settings.DJANGO_DATABASE_NAME,  # e.g. C:/github/projectdir/data/db.sqlite3
        "ENGINE": env_settings.DJANGO_DATABASE_ENGINE,  # "django.db.backends.sqlite3" for sqlite
        "USER": env_settings.DJANGO_DATABASE_USER,
        "PASSWORD": env_settings.DJANGO_DATABASE_PASSWORD,
        "HOST": env_settings.DJANGO_DATABASE_HOST,  # empty string for localhost.
        "PORT": env_settings.DJANGO_DATABASE_PORT,  # empty string for default.
    },
}
logger.warning(f"Environment is set to: {base_settings.APP_ENV}")
logger.warning(f"DATABASE ENGINE: {DATABASES['default'].get('ENGINE')}")
logger.warning(f"DATABASE NAME: {DATABASES['default'].get('NAME')}")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "collected_static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
