# Generated by Django 4.2.8 on 2023-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0008_dpslog_boss_id_dpslog_boss_name_dpslog_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
