# Generated by Django 4.2.8 on 2023-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0012_encounter_emoji_alter_dpslog_clear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
