# Generated by Django 4.2.8 on 2023-12-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0014_alter_emoji_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='cm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='dpsreport_boss_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
