# Generated by Django 4.2.8 on 2023-12-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0018_alter_dpslog_boss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='gw2_logs.instance'),
        ),
    ]
