# Generated by Django 4.2.8 on 2023-12-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0019_encounter_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpslog',
            name='boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dps_logs', to='gw2_logs.encounter'),
        ),
    ]
