# Generated by Django 4.2.8 on 2023-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0029_instanceclear_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='json_dump',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
