# Generated by Django 4.2.8 on 2023-12-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0042_emoji_animated'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='emoji_cm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_cm', to='gw2_logs.emoji'),
        ),
    ]
