# Generated by Django 4.2.8 on 2023-12-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0044_emoji_discord_id_cm_emoji_url_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='emoji_cm',
        ),
    ]
