# Generated by Django 4.2.8 on 2024-01-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0045_remove_encounter_emoji_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='discord_leaderboard_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
