# Generated by Django 4.2.8 on 2024-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0050_encounter_lb_encounter_lb_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpslog',
            name='emboldened',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpslog',
            name='final_health',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
