# Generated by Django 4.2.8 on 2024-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0056_alter_encounter_options_alter_dpslog_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecleargroup',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
