# Generated by Django 4.2.8 on 2024-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0059_alter_instancecleargroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecleargroup',
            name='success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
