# Generated by Django 4.2.8 on 2024-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0060_instancecleargroup_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceclear',
            name='core_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancecleargroup',
            name='core_player_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
