# Generated by Django 4.2.8 on 2024-03-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0066_encounter_use_total_clear_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='discord_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='gw2_logs.discordmessage'),
        ),
        migrations.CreateModel(
            name='InstanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('discord_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_group', to='gw2_logs.discordmessage')),
            ],
        ),
    ]
