# Generated by Django 4.2.8 on 2024-03-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0068_encounter_instance_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='instance_group',
            new_name='use_in_instance_group',
        ),
    ]
