# Generated by Django 4.2.8 on 2024-03-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0071_alter_encounter_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='gw2_logs.emoji'),
        ),
    ]
