# Generated by Django 4.2.8 on 2024-03-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0072_alter_encounter_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='discord_leaderboard_message_id',
        ),
    ]
