# Generated by Django 4.2.8 on 2024-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_logs', '0077_dpslog_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='ei_encounter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
